### ISSUE TITLE
Posso fazer oque falta ?

### ISSUE THREAD

**Issue by sombo20** [ErickWendel/websockets-with-nodejs-from-scratch#1]
**Olá mestre do nodejs  Erick Wendel**

Eu gostária de contribuir neste projecto tu vai aceitar meu pull ?

**Comment by ErickWendel** [comment]
Opa! Você pode contribuir e criar uma nova branch, assim posso deixar um aviso no readme

**Comment by sombo20** [comment]
**Farei isso!**
